###############################################################################
## dev 开发环境
###############################################################################

## 服务配置
server:
  port: 8090

## 数据库设置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: test
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      stat-view-servlet:
        url-pattern: "/druid/*"
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
          merge-sql: true

## mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**Mapper.xml
  typeAliasesPackage: com.example.standalone.model.*
  global-config:
    db-config:
      id-type: auto  #主键策略自增
      db-type: mysql
      field-strategy: not_null #实体属性为null不拼入sql语句中
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    ## 事务超时时间
    default-statement-timeout: 600
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl